const PRAY_DB_HOST = process.env.PRAY_DB_HOST;
const PRAY_DB_PORT = process.env.PRAY_DB_PORT;
const PRAY_DB_USER = process.env.PRAY_DB_USER;
const PRAY_DB_PASSWORD = process.env.PRAY_DB_PASSWORD;
const PRAY_DB_NAME = process.env.PRAY_DB_NAME;
export const IS_HAVE_PRAY_DATABASE_URL = !!PRAY_DB_HOST && !!PRAY_DB_PORT && !!PRAY_DB_USER && !!PRAY_DB_PASSWORD && !!PRAY_DB_NAME;
export const PRAY_DATABASE_URL = `postgresql://${PRAY_DB_USER}:${PRAY_DB_PASSWORD}@${PRAY_DB_HOST}:${PRAY_DB_PORT}/${PRAY_DB_NAME}`;

const INSTA_DB_HOST = process.env.INSTA_DB_HOST;
const INSTA_DB_PORT = process.env.INSTA_DB_PORT;
const INSTA_DB_USER = process.env.INSTA_DB_USER;
const INSTA_DB_PASSWORD = process.env.INSTA_DB_PASSWORD;
const INSTA_DB_NAME = process.env.INSTA_DB_NAME;
export const IS_HAVE_INSTA_DATABASE_URL = !!INSTA_DB_HOST && !!INSTA_DB_PORT && !!INSTA_DB_USER && !!INSTA_DB_PASSWORD && !!INSTA_DB_NAME;
export const INSTA_DATABASE_URL = `postgresql://${INSTA_DB_USER}:${INSTA_DB_PASSWORD}@${INSTA_DB_HOST}:${INSTA_DB_PORT}/${INSTA_DB_NAME}`;

const ANIME_DB_HOST = process.env.ANIME_DB_HOST;
const ANIME_DB_PORT = process.env.ANIME_DB_PORT;
const ANIME_DB_USER = process.env.ANIME_DB_USER;
const ANIME_DB_PASSWORD = process.env.ANIME_DB_PASSWORD;
const ANIME_DB_NAME = process.env.ANIME_DB_NAME;
export const IS_HAVE_ANIME_DATABASE_URL = !!ANIME_DB_HOST && !!ANIME_DB_PORT && !!ANIME_DB_USER && !!ANIME_DB_PASSWORD && !!ANIME_DB_NAME;
export const ANIME_DATABASE_URL = `postgresql://${ANIME_DB_USER}:${ANIME_DB_PASSWORD}@${ANIME_DB_HOST}:${ANIME_DB_PORT}/${ANIME_DB_NAME}`;

const MOVIE_DB_HOST = process.env.MOVIE_DB_HOST;
const MOVIE_DB_PORT = process.env.MOVIE_DB_PORT;
const MOVIE_DB_USER = process.env.MOVIE_DB_USER;
const MOVIE_DB_PASSWORD = process.env.MOVIE_DB_PASSWORD;
const MOVIE_DB_NAME = process.env.MOVIE_DB_NAME;
export const IS_HAVE_MOVIE_DATABASE_URL = !!MOVIE_DB_HOST && !!MOVIE_DB_PORT && !!MOVIE_DB_USER && !!MOVIE_DB_PASSWORD && !!MOVIE_DB_NAME;
export const MOVIE_DATABASE_URL = `postgresql://${MOVIE_DB_USER}:${MOVIE_DB_PASSWORD}@${MOVIE_DB_HOST}:${MOVIE_DB_PORT}/${MOVIE_DB_NAME}`;
